#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Oct 11 10:18:44 2019

@author: tristan

plotting sigma slope error and power output for different ray-tracer softwares
"""
import numpy as np
import matplotlib.pyplot as plt

tonatiuh = np.array([158480, 157237, 153172, 145673])
solarpilot = np.array([151320, 150580, 150100, 148700])
sunflower = np.array([157862, 157551, 156519, 154791])
SSE = np.array([0,1,2,3])


plt.figure()
plt.plot(SSE,tonatiuh/tonatiuh,'*-',label='Tonatiuh')
plt.plot(SSE,solarpilot/tonatiuh,'*-',label='SolarPilot')
plt.plot(SSE,sunflower/tonatiuh,'*-',label='Sunflower')
plt.grid(True)
plt.legend()
plt.show()
